### ISSUE TITLE
AttributeError: 'bool' object has no attribute '__call__'

### ISSUE THREAD

**Issue by centric-jim** [lingthio/Flask-User#108]
I thought this issue has been previously addressed:
(my_app) ~/dev/my_app $ ./runserver.sh 
- Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
- Restarting with stat
- Debugger is active!
- Debugger pin code: 173-922-105

127.0.0.1 - - [25/Dec/2015 21:51:47] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jimm/dev/my_app/app/core/views.py", line 18, in home_page
    return render_template('core/home_page.html')
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jimm/Envs/my_app/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jimm/dev/my_app/app/templates/core/home_page.html", line 1, in top-level template code
    {% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}
  File "/home/jimm/dev/my_app/app/templates/common/page_base.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/jimm/dev/my_app/app/templates/layout.html", line 24, in top-level template code
    {% block body %}
  File "/home/jimm/dev/my_app/app/templates/layout.html", line 29, in block "body"
    {% if current_user.is_authenticated() %}
AttributeError: 'bool' object has no attribute '__call__'
127.0.0.1 - - [25/Dec/2015 21:51:47] "GET /?**debugger**=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Dec/2015 21:51:47] "GET /?**debugger**=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Dec/2015 21:51:47] "GET /?**debugger**=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Dec/2015 21:51:47] "GET /?**debugger**=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [25/Dec/2015 21:51:47] "GET /?**debugger**=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

I tried upgrading to Flask-User 0.6.8 but this issue is still there.  I was really hoping for something that 'just worked' so that I could build on this and learn how to implement user and role based access

**Comment by lingthio** [comment]
In older versions of flask_login, `is_authenticated` is a function. In newer versions of flask_login, `is_authenticated` is a property. Simply change `is_authenticated()` to `is_authenticated` when using newer versions of flask_login.
