### ISSUE TITLE
Blueprint Collisions 

### ISSUE THREAD

**Issue by ianzimmerman** [lingthio/Flask-User#118]
```
[Thu May 19 01:15:28.088805 2016] [:error] [pid 9708] [remote 136.243.152.18:54250] mod_wsgi (pid=9708): Target WSGI script '/opt/python/current/app/application.py' cannot be loaded as Python module.
[Thu May 19 01:15:28.088868 2016] [:error] [pid 9708] [remote 136.243.152.18:54250] mod_wsgi (pid=9708): Exception occurred processing WSGI script '/opt/python/current/app/application.py'.
[Thu May 19 01:15:28.088902 2016] [:error] [pid 9708] [remote 136.243.152.18:54250] Traceback (most recent call last):
[Thu May 19 01:15:28.088970 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]   File "/opt/python/current/app/application.py", line 2, in <module>
[Thu May 19 01:15:28.088979 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]     from gifc import app as application
[Thu May 19 01:15:28.089011 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]   File "/opt/python/current/app/gifc/__init__.py", line 48, in <module>
[Thu May 19 01:15:28.089019 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]     user_manager = UserManager(db_adapter, app=app) # password_validator=my_password_validator
[Thu May 19 01:15:28.089058 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]   File "/opt/python/run/venv/lib/python3.4/site-packages/flask_user/__init__.py", line 53, in __init__
[Thu May 19 01:15:28.089066 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]     self.init_app(app, db_adapter, **kwargs)
[Thu May 19 01:15:28.089094 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]   File "/opt/python/run/venv/lib/python3.4/site-packages/flask_user/__init__.py", line 173, in init_app
[Thu May 19 01:15:28.089101 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]     app.register_blueprint(blueprint)
[Thu May 19 01:15:28.089133 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]   File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 62, in wrapper_func
[Thu May 19 01:15:28.089140 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]     return f(self, *args, **kwargs)
[Thu May 19 01:15:28.089169 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]   File "/opt/python/run/venv/lib/python3.4/site-packages/flask/app.py", line 885, in register_blueprint
[Thu May 19 01:15:28.089175 2016] [:error] [pid 9708] [remote 136.243.152.18:54250]     (blueprint, self.blueprints[blueprint.name], blueprint.name)
[Thu May 19 01:15:28.089199 2016] [:error] [pid 9708] [remote 136.243.152.18:54250] AssertionError: A blueprint's name collision occurred between <flask.blueprints.Blueprint object at 0x7f7d9aa710b8> and <flask.blueprints.Blueprint object at 0x7f7d9b053b38>.  Both share the same name "flask_user".  Blueprints that are created on the fly need unique names.
```

App works locally, but when deployed to AWS above error occurs

```
# Setup Flask-User
db_adapter = SQLAlchemyAdapter(db, User)        # Register the User model
user_manager = UserManager(db_adapter, app)
```

Deploying to AWS

**Comment by lingthio** [comment]
My apologies for responding so late. I'm not familiar with AWS and was wondering if and how you have resolved this issue?

**Comment by ianzimmerman** [comment]
Thanks for looking, I had to move flask to an app factory method to resolve multiple instances at once on AWS.

**Comment by lingthio** [comment]
Thanks. I'm closing this issue.
