### ISSUE TITLE
UserManager __init__ error

### ISSUE THREAD

**Issue by abprojects** [lingthio/Flask-User#221]
I recently migrated to V1.0 and have been running into this error. I use application factory set up and use with app.app_context() statement (don't know if this is relevant to the error or not). I was wondering if anyone has experienced this or if anyone could help figure out how to debug this one. Any help would be appreciated as I have been stuck on this one for a while.

**Comment by inspiretk** [comment]
Whats in your File "prodserver.py" - show code

**Comment by abprojects** [comment]
File prodserver.py: 


app = create_app('herokuprod')


manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()

**Comment by abprojects** [comment]
Yes, I used v0.6 before. I got an error with that version, but can't recall the exact error it produced.

I'm thrown off too because I only provided 3 args. After doing some research on other people that have had similar errors with different packages, it seems that the problem has something to do with the implied "self" in the __init__ function. 

The only difference I see with how my create_app func is set up and the way others are (including the example in the docs) is the with app.app_context() statement used. I'm wondering if the problem has something to do with the arg app. I've tried removing it with no luck.

**Comment by inspiretk** [comment]
Maybe check this:
* You have: user_manager = UserManager(app, db, User)
* The UserManager needs 4 inputs: https://github.com/lingthio/Flask-User/blob/master/flask_user/user_manager.py
** See Example part: ``user_manager = UserManager(app, db, User, UserEmailClass=UserEmail)``
* Maybe? Test and see what happens with 4 inputs, the UserEmailClass=UserEmail. That's just my hunch. I havn't done what you're doing. I've just got the basic flask setup only, and that's working on my side.
If you want, you can post your code somewhere and I'll see if I can get it working on my side.

**Comment by abprojects** [comment]
I tried adding in the kwarg UserEmailClass and it produced this error:

Traceback (most recent call last):
  File "prodserver.py", line 10, in <module>
    app = create_app('herokuprod')
  File "/home/brucewayne/peak/peak/__init__.py", line 95, in create_app
    user_manager = UserManager(app, db, User, UserEmailClass=None)
TypeError: __init__() takes at most 3 arguments (5 given)

I'm thinking it definitely has something to do with an argument in there that isn't explicit (either the self or the app arg).

**Comment by inspiretk** [comment]
Yes you are right. Now it says 5 given, whereas before was 4 given. You need to find where that extra input is coming from.

I think somewhere, its giving 4 inputs, instead of 3.
That shows 4 inputs, but it needs 3 inputs. 

What's line 95? File "/home/brucewayne/peak/peak/init.py", line 95, in create_app

Also, have you tried just getting the basic working first? Then migrate across? What are you migrating from? Maybe since you're migrating, you need to run migration code then when it's migrated, you run the running code. Maybe there's a conflict between migration and running code.

Hopefully somebody that's a pro will come and see you and help you.
