### ISSUE TITLE
AttributeError: 'UserManager' object has no attribute 'password_hash'

### ISSUE THREAD

**Issue by wandonye** [lingthio/Flask-User#56]
Got the following error when run a test. 

    Traceback (most recent call last):
    File "//anaconda/envs/vshare/lib/python3.4/site-packages/_pytest/config.py", line 513, in getconftestmodules
          return self._path2confmods[path]
    KeyError: local('/Users/wandonye/flask/projects/dimension5/tests')

    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "//anaconda/envs/vshare/lib/python3.4/site-packages/_pytest/config.py", line 537, in importconftest
        return self._conftestpath2mod[conftestpath]
    KeyError: local('/Users/wandonye/flask/projects/dimension5/tests/conftest.py')

    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "//anaconda/envs/vshare/lib/python3.4/site-packages/_pytest/config.py", line 543, in importconftest
        mod = conftestpath.pyimport()
      File "//anaconda/envs/vshare/lib/python3.4/site-packages/py/_path/local.py", line 641, in pyimport
        __import__(modname)
      File "/Users/wandonye/flask/projects/dimension5/tests/conftest.py", line 12, in <module>
        from .factories import UserFactory
      File "/Users/wandonye/flask/projects/dimension5/tests/factories.py", line 16, in <module>
        class UserFactory(BaseFactory):
      File "/Users/wandonye/flask/projects/dimension5/tests/factories.py", line 19, in UserFactory
        password = user_manager.hash_password('example')
      File "//anaconda/envs/vshare/lib/python3.4/site-packages/flask_user/__init__.py", line 215, in hash_password
        return passwords.hash_password(self, password)
      File "//anaconda/envs/vshare/lib/python3.4/site-packages/flask_user/passwords.py", line 19, in hash_password
        if user_manager.password_hash == 'plaintext':
    AttributeError: 'UserManager' object has no attribute 'password_hash'
    ERROR: could not load /Users/wandonye/flask/projects/dimension5/tests/conftest.py

The code in conftest.py is like this:

    class BaseFactory(SQLAlchemyModelFactory):
        class Meta:
            abstract = True
            sqlalchemy_session = db.session
    
    class UserFactory(BaseFactory):
        username = Sequence(lambda n: "user{0}".format(n))
        email = Sequence(lambda n: "user{0}@example.com".format(n))
        password = user_manager.hash_password('example')
        is_enabled = True
    
        class Meta:
            model = User

Originally it was
      
    password = PostGenerationMethodCall('set_password', 'example')

But I have to change it because User does not have 'set_password'. If I define one in the User class, then I have to import user_manager in the models file of User, which will create a loop of import.

**Comment by lingthio** [comment]
My apologies for the (very) late response.
The only scenario I can find for this to happen is if:
- you called `user_manager = UserManager()` without the `app` parameter
- forgot to call the `UserManager.init_app(app)` function
- and immediately user `user_manager.hash_password()`.

Two ways to fix this:
```
user_manager = UserManager(db_adapter, app)
hashed_password = user_manager.hash_password(the_password)
```

or:
```
user_manager = UserManager(db_adapter)
user_manager.init_app(app)
hashed_password = user_manager.hash_password(the_password)
```

**Comment by ayushsingh-07** [comment]
@lingthio  this does not work, i think there might be some import statement missing.....i just can't figure that out

@wandonye did you figure out the answer??
