### ISSUE TITLE
Throwing sqlalchemy.exc.IntegrityError in user's face

### ISSUE THREAD

**Issue by Xender** [lingthio/Flask-User#90]
When trying to register new user with same username as existing one, I have following traceback:

```
Traceback (most recent call last):
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/<path>/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/<path>/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/<path>/venv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/<path>/venv/lib/python3.4/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/<path>/venv/lib/python3.4/site-packages/flask_user/views.py", line 417, in register
    db_adapter.commit()
  File "/<path>/venv/lib/python3.4/site-packages/flask_user/db_adapters.py", line 116, in commit
    self.db.session.commit()
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 781, in _emit_insert_statements
    execute(statement, params)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/<path>/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user_auth.username [SQL: 'INSERT INTO user_auth (user_id, username, password, reset_password_token) VALUES (?, ?, ?, ?)'] [parameters: (None, 'qwerty', '$2a$12$hlja9MU5dPmCI8zNkiaGOes.0D51oSl4hIZMYRT4xWIFQJ1S0iON6', '')]
```

This basically shouldn't happen, as there are form validators for unique username and email.
I'm using separate `User`, `UserAuth`, `UserEmail` and `Role` models.

**Comment by NinjaKitou** [comment]
Hello,

I am having a similar issue, I am not 100% sure, but it looks like it's related to this method:

``` python
def username_is_available(self, new_username):
    """ Return True if new_username does not exist or if new_username equals old_username.
        Return False otherwise."""
    # Allow user to change username to the current username
    if _call_or_get(current_user.is_authenticated):
        current_username = current_user.user_auth.username if self.db_adapter.UserAuthClass and hasattr(current_user, 'user_auth') else current_user.username
        if new_username == current_username:
            return True
    # See if new_username is available
    return self.find_user_by_username(new_username)==None
```

in the case of an invite, the invited user is authenticated, and I guess it's username in the session is the one from the user who performed the invitation. So if the invited user decides to take exactly the same name as the person who invites, it returns True, and bypass the 'username already exists' check in the form validation.

This is leading to trying to insert in the database, but it fails because of the unique constraint.

I did not set the unique constraint at the beginning, and the consequences were even worse, leading to users having the same username.... this is fixed :)
